[project]
name = "sunsets-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "astral>=2.2,<3",
    "ics>=0.7.2",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
